### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by ahmedbilal** [FozanGardezi/Flask#4]
```
(fozan-flask-iybhRKFT-py3.8) ➜  Flask git:(master) ✗ python app/__init__.py
Traceback (most recent call last):
  File "app/__init__.py", line 2, in <module>
    import config
ModuleNotFoundError: No module named 'config'
```

```
(fozan-flask-iybhRKFT-py3.8) ➜  Flask git:(master) ✗ export FLASK_APP=app 
(fozan-flask-iybhRKFT-py3.8) ➜  Flask git:(master) ✗ flask run
 * Serving Flask app "app"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Flask-1.1.1-py3.8.egg/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/meow/Desktop/temp/Flask/app/__init__.py", line 3, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
```

**Comment by FozanGardezi** [comment]
The config.py module is in the home directory. It is also present in the repository.
